### ISSUE TITLE
Quick Search Issue

### ISSUE THREAD

**Issue by danswano** [rcdesign-cemetery/vb-sphinx_search#13]
Hello,

There is a problem with quick search in the product, when i do a quick search it display the results as posts instead of threads, after disabling the product quick search back to normal and display results as threads, any fix for this please?

Thank you very much. :)

**Comment by puzrin** [comment]
It's a special feature. Because it's impossible to find result in long threads without it.

IMHO, vB search design is quite stupid & outdated. It contains lot of useless things (like order by thread name and user), and lack of useful one. I try to improve situation.

This mod is NOT 100% the same as original search.

**Comment by danswano** [comment]
Seems good, but is there any edit i can do to revert the threads only search instead of posts please? it works fine in advanced search but i want quick search as threads. :)

**Comment by puzrin** [comment]
Not right now. This mod will be seriously rewritten in next month. It seems more easy to write search from scratch, than try to improve vb alien logic :) . I've added your note to wiki todo: https://github.com/rcdesign/vb-sphinx_search/wiki

**Comment by danswano** [comment]
Thanks for the heads up buddy, i really appreciate your efforts in this mod, hope to see an awesome improvement soon. :)
